import {
  IconMap,
  IconSettings,
  IconFolder,
  IconCat,
  IconGrave,
  IconReportMoney,
  IconBuilding,
} from '@tabler/icons-react'
import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  CircuitBoardIcon,
  Clock,
  Command,
  CreditCard,
  ExternalLink,
  File,
  FileText,
  Folder,
  HelpCircle,
  History,
  Image,
  Laptop,
  LayoutDashboard,
  Link,
  List,
  Lock,
  Loader2,
  LogIn,
  LucideProps,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  User,
  User2,
  X,
} from 'lucide-react'

export type Icon = LucideProps

export const Icons = {
  dashboard: LayoutDashboard,
  logo: Command,
  login: LogIn,
  close: X,
  profile: User2,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  list: List,
  lock: Lock,
  link: Link,
  check: Check,
  application: CircuitBoardIcon,
  folder: Folder,
  // Navigation history icons
  history: History,
  clock: Clock,
  externalLink: ExternalLink,
  fileText: FileText,
  // Tabler icons
  tablerMap: IconMap,
  tablerSettings: IconSettings,
  tablerFolder: IconFolder,
  IconCat: IconCat,
  IconGrave: IconGrave,
  IconReportMoney: IconReportMoney,
  IconBuilding: IconBuilding,
} as const

export type IconKey = keyof typeof Icons
