// <auto-generated />
using System;
using Frotas.API.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Frotas.API.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251120171049_AddDocumentosToSeguro")]
    partial class AddDocumentosToSeguro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cargo", "Base");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.CodigoPostal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Localidade")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodigoPostal", "Base");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Concelho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DistritoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistritoId");

                    b.ToTable("Concelho", "Base");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Conservatoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodigoPostalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConcelhoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FreguesiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Morada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoPostalId");

                    b.HasIndex("ConcelhoId");

                    b.HasIndex("FreguesiaId");

                    b.ToTable("Conservatoria", "Base");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Delegacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodigoPostalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoHttp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Localidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Morada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PaisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoPostalId");

                    b.HasIndex("PaisId");

                    b.ToTable("Delegacao", "Base");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Distrito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PaisId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Distrito", "Base");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Entidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodigoPostalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoHttp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Localidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Morada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PaisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoPostalId");

                    b.HasIndex("PaisId");

                    b.ToTable("Entidade", "Base");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Fornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("CodigoPostalCargaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodigoPostalEscritorioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MesmoEndereco")
                        .HasColumnType("bit");

                    b.Property<string>("MoradaCarga")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoradaEscritorio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumContribuinte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PaisCargaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PaisEscritorioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telemovel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoPostalCargaId");

                    b.HasIndex("CodigoPostalEscritorioId");

                    b.HasIndex("PaisCargaId");

                    b.HasIndex("PaisEscritorioId");

                    b.ToTable("Fornecedor", "Base");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Freguesia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConcelhoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConcelhoId");

                    b.ToTable("Freguesia", "Base");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("CargoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodigoPostalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DelegacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FreguesiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Morada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("CodigoPostalId");

                    b.HasIndex("DelegacaoId");

                    b.HasIndex("FreguesiaId");

                    b.ToTable("Funcionario", "Base");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Garantia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Anos")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kms")
                        .HasColumnType("int");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Garantia", "Base");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Localizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodigoPostalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FreguesiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Morada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoPostalId");

                    b.HasIndex("FreguesiaId");

                    b.ToTable("Localizacao", "Base");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Pais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prefixo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pais", "Base");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Rua", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodigoPostalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FreguesiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoPostalId");

                    b.HasIndex("FreguesiaId");

                    b.ToTable("Rua", "Base");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Setor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Setor", "Base");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.TaxaIva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TaxaIva", "Base");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Terceiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodigoPostalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Morada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoPostalId");

                    b.ToTable("Terceiro", "Base");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categoria", "Frotas");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.Combustivel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Combustivel", "Frotas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Gasolina 95"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Gasolina 98"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Gasolina E10"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "E85"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Gasóleo Simples"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Gasóleo Aditivado"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Biodiesel"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "GPL/Autogás"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "GNV/Gás Natural Veicular"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000a"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "ADBlue"
                        });
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.Cor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cor", "Frotas");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.Equipamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Garantia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Obs")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipamento", "Frotas");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.Marca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Marca", "Frotas");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.Modelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MarcaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.ToTable("Modelo", "Frotas");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.Peca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Anos")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Custo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CustoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Designacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kms")
                        .HasColumnType("int");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TaxaIvaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TaxaIvaId");

                    b.ToTable("Peca", "Frotas");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.Seguradora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Seguradora", "Frotas");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.Seguro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apolice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AssistenciaViagem")
                        .HasColumnType("bit");

                    b.Property<bool>("CartaVerde")
                        .HasColumnType("bit");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CustoAnual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicial")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documentos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MetodoPagamento")
                        .HasColumnType("int");

                    b.Property<int>("Periodicidade")
                        .HasColumnType("int");

                    b.Property<string>("RiscosCobertos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SeguradoraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorCobertura")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SeguradoraId");

                    b.ToTable("Seguro", "Frotas");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Anos")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Custo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CustoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Designacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kms")
                        .HasColumnType("int");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TaxaIvaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TaxaIvaId");

                    b.ToTable("Servico", "Frotas");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.TipoViatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoriaInspecao")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TipoViatura", "Frotas");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.Viatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AnoFabrico")
                        .HasColumnType("int");

                    b.Property<int?>("AnoImpostoCirculacao")
                        .HasColumnType("int");

                    b.Property<int?>("AnoImpostoSelo")
                        .HasColumnType("int");

                    b.Property<decimal?>("Autonomia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CapacidadeBateria")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CargaUtil")
                        .HasColumnType("int");

                    b.Property<string>("CartaoCombustivel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Cilindrada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CombustivelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Comprimento")
                        .HasColumnType("int");

                    b.Property<Guid?>("ConservatoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ConsumoEletrico")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ConsumoMedio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Contrato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Custo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DataAquisicao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInicial")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataLivrete")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataValidadeSelo")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DelegacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DespesasIncluidas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EmissoesCO2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("FornecedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Largura")
                        .HasColumnType("int");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LocalizacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Lotacao")
                        .HasColumnType("int");

                    b.Property<Guid>("MarcaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Marketing")
                        .HasColumnType("bit");

                    b.Property<string>("Matricula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Mercadorias")
                        .HasColumnType("bit");

                    b.Property<int?>("MesFabrico")
                        .HasColumnType("int");

                    b.Property<Guid>("ModeloId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("NMotor")
                        .HasColumnType("int");

                    b.Property<int?>("NQuadro")
                        .HasColumnType("int");

                    b.Property<int?>("NRendas")
                        .HasColumnType("int");

                    b.Property<string>("NotasAdicionais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Numero")
                        .HasColumnType("int");

                    b.Property<bool>("OpcaoCompra")
                        .HasColumnType("bit");

                    b.Property<string>("PadraoCO2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PneusFrente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PneusTras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Potencia")
                        .HasColumnType("int");

                    b.Property<int?>("PotenciaCombinada")
                        .HasColumnType("int");

                    b.Property<int?>("PotenciaMotorEletrico")
                        .HasColumnType("int");

                    b.Property<Guid?>("SetorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Tara")
                        .HasColumnType("int");

                    b.Property<decimal?>("TempoCarregamento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("TerceiroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TipoPropulsao")
                        .HasColumnType("int");

                    b.Property<Guid?>("TipoViaturaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("URLImagem1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URLImagem2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ValorRenda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorResidual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorTotalContrato")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VoltagemTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CombustivelId");

                    b.HasIndex("ConservatoriaId");

                    b.HasIndex("CorId");

                    b.HasIndex("DelegacaoId");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("LocalizacaoId");

                    b.HasIndex("MarcaId");

                    b.HasIndex("ModeloId");

                    b.HasIndex("SetorId");

                    b.HasIndex("TerceiroId");

                    b.HasIndex("TipoViaturaId");

                    b.ToTable("Viatura", "Frotas");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.ViaturaAcidente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CodigoPostalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConcelhoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Culpa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoAcidente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaoDanos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FreguesiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Local")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalReparacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ViaturaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CodigoPostalId");

                    b.HasIndex("ConcelhoId");

                    b.HasIndex("FreguesiaId");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("ViaturaId");

                    b.ToTable("ViaturaAcidente", "Frotas");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.ViaturaCondutor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ViaturaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("ViaturaId", "FuncionarioId")
                        .IsUnique();

                    b.ToTable("ViaturaCondutor", "Frotas");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.ViaturaEquipamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EquipamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ViaturaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EquipamentoId");

                    b.HasIndex("ViaturaId", "EquipamentoId")
                        .IsUnique();

                    b.ToTable("ViaturaEquipamento", "Frotas");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.ViaturaGarantia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GarantiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ViaturaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GarantiaId");

                    b.HasIndex("ViaturaId", "GarantiaId")
                        .IsUnique();

                    b.ToTable("ViaturaGarantia", "Frotas");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.ViaturaInspecao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInspecao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataProximaInspecao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Documentos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Resultado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ViaturaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ViaturaId");

                    b.ToTable("ViaturaInspecao", "Frotas");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.ViaturaMulta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Local")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ViaturaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("ViaturaId");

                    b.ToTable("ViaturaMulta", "Frotas");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.ViaturaSeguro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SeguroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ViaturaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SeguroId");

                    b.HasIndex("ViaturaId", "SeguroId")
                        .IsUnique();

                    b.ToTable("ViaturaSeguro", "Frotas");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Concelho", b =>
                {
                    b.HasOne("Frotas.API.Domain.Entities.Base.Distrito", "Distrito")
                        .WithMany("Concelhos")
                        .HasForeignKey("DistritoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Distrito");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Conservatoria", b =>
                {
                    b.HasOne("Frotas.API.Domain.Entities.Base.CodigoPostal", "CodigoPostal")
                        .WithMany()
                        .HasForeignKey("CodigoPostalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Frotas.API.Domain.Entities.Base.Concelho", "Concelho")
                        .WithMany()
                        .HasForeignKey("ConcelhoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Frotas.API.Domain.Entities.Base.Freguesia", "Freguesia")
                        .WithMany()
                        .HasForeignKey("FreguesiaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CodigoPostal");

                    b.Navigation("Concelho");

                    b.Navigation("Freguesia");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Delegacao", b =>
                {
                    b.HasOne("Frotas.API.Domain.Entities.Base.CodigoPostal", "CodigoPostal")
                        .WithMany()
                        .HasForeignKey("CodigoPostalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Frotas.API.Domain.Entities.Base.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CodigoPostal");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Distrito", b =>
                {
                    b.HasOne("Frotas.API.Domain.Entities.Base.Pais", "Pais")
                        .WithMany("Distritos")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Entidade", b =>
                {
                    b.HasOne("Frotas.API.Domain.Entities.Base.CodigoPostal", "CodigoPostal")
                        .WithMany()
                        .HasForeignKey("CodigoPostalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Frotas.API.Domain.Entities.Base.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CodigoPostal");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Fornecedor", b =>
                {
                    b.HasOne("Frotas.API.Domain.Entities.Base.CodigoPostal", "CodigoPostalCarga")
                        .WithMany()
                        .HasForeignKey("CodigoPostalCargaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Frotas.API.Domain.Entities.Base.CodigoPostal", "CodigoPostalEscritorio")
                        .WithMany()
                        .HasForeignKey("CodigoPostalEscritorioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Frotas.API.Domain.Entities.Base.Pais", "PaisCarga")
                        .WithMany()
                        .HasForeignKey("PaisCargaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Frotas.API.Domain.Entities.Base.Pais", "PaisEscritorio")
                        .WithMany()
                        .HasForeignKey("PaisEscritorioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CodigoPostalCarga");

                    b.Navigation("CodigoPostalEscritorio");

                    b.Navigation("PaisCarga");

                    b.Navigation("PaisEscritorio");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Freguesia", b =>
                {
                    b.HasOne("Frotas.API.Domain.Entities.Base.Concelho", "Concelho")
                        .WithMany("Freguesias")
                        .HasForeignKey("ConcelhoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Concelho");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Funcionario", b =>
                {
                    b.HasOne("Frotas.API.Domain.Entities.Base.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Frotas.API.Domain.Entities.Base.CodigoPostal", "CodigoPostal")
                        .WithMany()
                        .HasForeignKey("CodigoPostalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Frotas.API.Domain.Entities.Base.Delegacao", "Delegacao")
                        .WithMany()
                        .HasForeignKey("DelegacaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Frotas.API.Domain.Entities.Base.Freguesia", "Freguesia")
                        .WithMany()
                        .HasForeignKey("FreguesiaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("CodigoPostal");

                    b.Navigation("Delegacao");

                    b.Navigation("Freguesia");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Localizacao", b =>
                {
                    b.HasOne("Frotas.API.Domain.Entities.Base.CodigoPostal", "CodigoPostal")
                        .WithMany()
                        .HasForeignKey("CodigoPostalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Frotas.API.Domain.Entities.Base.Freguesia", "Freguesia")
                        .WithMany()
                        .HasForeignKey("FreguesiaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CodigoPostal");

                    b.Navigation("Freguesia");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Rua", b =>
                {
                    b.HasOne("Frotas.API.Domain.Entities.Base.CodigoPostal", "CodigoPostal")
                        .WithMany("Ruas")
                        .HasForeignKey("CodigoPostalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Frotas.API.Domain.Entities.Base.Freguesia", "Freguesia")
                        .WithMany("Ruas")
                        .HasForeignKey("FreguesiaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CodigoPostal");

                    b.Navigation("Freguesia");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Terceiro", b =>
                {
                    b.HasOne("Frotas.API.Domain.Entities.Base.CodigoPostal", "CodigoPostal")
                        .WithMany()
                        .HasForeignKey("CodigoPostalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CodigoPostal");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.Modelo", b =>
                {
                    b.HasOne("Frotas.API.Domain.Entities.Frotas.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.Peca", b =>
                {
                    b.HasOne("Frotas.API.Domain.Entities.Base.TaxaIva", "TaxaIva")
                        .WithMany()
                        .HasForeignKey("TaxaIvaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("TaxaIva");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.Seguro", b =>
                {
                    b.HasOne("Frotas.API.Domain.Entities.Frotas.Seguradora", "Seguradora")
                        .WithMany()
                        .HasForeignKey("SeguradoraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Seguradora");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.Servico", b =>
                {
                    b.HasOne("Frotas.API.Domain.Entities.Base.TaxaIva", "TaxaIva")
                        .WithMany()
                        .HasForeignKey("TaxaIvaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("TaxaIva");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.Viatura", b =>
                {
                    b.HasOne("Frotas.API.Domain.Entities.Frotas.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Frotas.API.Domain.Entities.Frotas.Combustivel", "Combustivel")
                        .WithMany()
                        .HasForeignKey("CombustivelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Frotas.API.Domain.Entities.Base.Conservatoria", "Conservatoria")
                        .WithMany()
                        .HasForeignKey("ConservatoriaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Frotas.API.Domain.Entities.Frotas.Cor", "Cor")
                        .WithMany()
                        .HasForeignKey("CorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Frotas.API.Domain.Entities.Base.Delegacao", "Delegacao")
                        .WithMany()
                        .HasForeignKey("DelegacaoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Frotas.API.Domain.Entities.Base.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Frotas.API.Domain.Entities.Base.Localizacao", "Localizacao")
                        .WithMany()
                        .HasForeignKey("LocalizacaoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Frotas.API.Domain.Entities.Frotas.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Frotas.API.Domain.Entities.Frotas.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Frotas.API.Domain.Entities.Base.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Frotas.API.Domain.Entities.Base.Terceiro", "Terceiro")
                        .WithMany()
                        .HasForeignKey("TerceiroId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Frotas.API.Domain.Entities.Frotas.TipoViatura", "TipoViatura")
                        .WithMany()
                        .HasForeignKey("TipoViaturaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Categoria");

                    b.Navigation("Combustivel");

                    b.Navigation("Conservatoria");

                    b.Navigation("Cor");

                    b.Navigation("Delegacao");

                    b.Navigation("Fornecedor");

                    b.Navigation("Localizacao");

                    b.Navigation("Marca");

                    b.Navigation("Modelo");

                    b.Navigation("Setor");

                    b.Navigation("Terceiro");

                    b.Navigation("TipoViatura");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.ViaturaAcidente", b =>
                {
                    b.HasOne("Frotas.API.Domain.Entities.Base.CodigoPostal", "CodigoPostal")
                        .WithMany()
                        .HasForeignKey("CodigoPostalId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Frotas.API.Domain.Entities.Base.Concelho", "Concelho")
                        .WithMany()
                        .HasForeignKey("ConcelhoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Frotas.API.Domain.Entities.Base.Freguesia", "Freguesia")
                        .WithMany()
                        .HasForeignKey("FreguesiaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Frotas.API.Domain.Entities.Base.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Frotas.API.Domain.Entities.Frotas.Viatura", "Viatura")
                        .WithMany("ViaturaAcidentes")
                        .HasForeignKey("ViaturaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CodigoPostal");

                    b.Navigation("Concelho");

                    b.Navigation("Freguesia");

                    b.Navigation("Funcionario");

                    b.Navigation("Viatura");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.ViaturaCondutor", b =>
                {
                    b.HasOne("Frotas.API.Domain.Entities.Base.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Frotas.API.Domain.Entities.Frotas.Viatura", "Viatura")
                        .WithMany("ViaturaCondutores")
                        .HasForeignKey("ViaturaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Viatura");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.ViaturaEquipamento", b =>
                {
                    b.HasOne("Frotas.API.Domain.Entities.Frotas.Equipamento", "Equipamento")
                        .WithMany("ViaturaEquipamentos")
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Frotas.API.Domain.Entities.Frotas.Viatura", "Viatura")
                        .WithMany("ViaturaEquipamentos")
                        .HasForeignKey("ViaturaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Equipamento");

                    b.Navigation("Viatura");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.ViaturaGarantia", b =>
                {
                    b.HasOne("Frotas.API.Domain.Entities.Base.Garantia", "Garantia")
                        .WithMany("ViaturaGarantias")
                        .HasForeignKey("GarantiaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Frotas.API.Domain.Entities.Frotas.Viatura", "Viatura")
                        .WithMany("ViaturaGarantias")
                        .HasForeignKey("ViaturaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Garantia");

                    b.Navigation("Viatura");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.ViaturaInspecao", b =>
                {
                    b.HasOne("Frotas.API.Domain.Entities.Frotas.Viatura", "Viatura")
                        .WithMany("ViaturaInspecoes")
                        .HasForeignKey("ViaturaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Viatura");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.ViaturaMulta", b =>
                {
                    b.HasOne("Frotas.API.Domain.Entities.Base.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Frotas.API.Domain.Entities.Frotas.Viatura", "Viatura")
                        .WithMany("ViaturaMultas")
                        .HasForeignKey("ViaturaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Viatura");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.ViaturaSeguro", b =>
                {
                    b.HasOne("Frotas.API.Domain.Entities.Frotas.Seguro", "Seguro")
                        .WithMany("ViaturaSeguros")
                        .HasForeignKey("SeguroId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Frotas.API.Domain.Entities.Frotas.Viatura", "Viatura")
                        .WithMany("ViaturaSeguros")
                        .HasForeignKey("ViaturaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Seguro");

                    b.Navigation("Viatura");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.CodigoPostal", b =>
                {
                    b.Navigation("Ruas");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Concelho", b =>
                {
                    b.Navigation("Freguesias");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Distrito", b =>
                {
                    b.Navigation("Concelhos");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Freguesia", b =>
                {
                    b.Navigation("Ruas");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Garantia", b =>
                {
                    b.Navigation("ViaturaGarantias");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Base.Pais", b =>
                {
                    b.Navigation("Distritos");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.Equipamento", b =>
                {
                    b.Navigation("ViaturaEquipamentos");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.Seguro", b =>
                {
                    b.Navigation("ViaturaSeguros");
                });

            modelBuilder.Entity("Frotas.API.Domain.Entities.Frotas.Viatura", b =>
                {
                    b.Navigation("ViaturaAcidentes");

                    b.Navigation("ViaturaCondutores");

                    b.Navigation("ViaturaEquipamentos");

                    b.Navigation("ViaturaGarantias");

                    b.Navigation("ViaturaInspecoes");

                    b.Navigation("ViaturaMultas");

                    b.Navigation("ViaturaSeguros");
                });
#pragma warning restore 612, 618
        }
    }
}
